name: Build Go
on:
  push:
    branches: [ 'main', 'master' ]
    tags: [ 'v*' ]

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: jimschubert/.workflows/.github/workflows/go-build.yml@main
    secrets: inherit
